name: Default Backend Test

on:
  pull_request:
    branches:
      - main
      - "release/*.*.*"
    paths:
      - "web/**"

jobs:
  skip-go-static-checks:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Not required"'

  skip-go-tests:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Not required"'
